### ISSUE TITLE
TypeError: '020001.jpg' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)

### ISSUE THREAD

**Issue by c1a1o1** [Prinsphield/DNA-GAN#1]
TypeError: '020001.jpg' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)

create_tfrecords.py

tf1.4   python3.5.

**Comment by shbnm21** [comment]
@c1a1o1 how did you resolve TypeError?

I am getting same error.

**Comment by zhangqian001** [comment]
> @c1a1o1 how did you resolve TypeError?
> 
> I am getting same error.



> TypeError: '020001.jpg' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)
> 
> create_tfrecords.py
> 
> tf1.4 python3.5.

I also get this error.
